/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -v -c SearchIf -p searchif.h:searchif.cpp com.zeal.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef SEARCHIF_H_1372542167
#define SEARCHIF_H_1372542167

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.zeal
 */
class SearchIf: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.zeal"; }

public:
    SearchIf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~SearchIf();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> ping()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("ping"), argumentList);
    }

    inline QDBusPendingReply<> search(const QString &name)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(name);
        return asyncCallWithArgumentList(QLatin1String("search"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace com {
  typedef ::SearchIf zeal;
}
#endif
