/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c SearchIfAdaptor -a searchifadaptor.h:searchifadaptor.cpp com.zeal.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SEARCHIFADAPTOR_H_1372542167
#define SEARCHIFADAPTOR_H_1372542167

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.zeal
 */
class SearchIfAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.zeal")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.zeal\">\n"
"    <method name=\"search\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"    </method>\n"
"    <method name=\"ping\"/>\n"
"  </interface>\n"
        "")
public:
    SearchIfAdaptor(QObject *parent);
    virtual ~SearchIfAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void ping();
    void search(const QString &name);
Q_SIGNALS: // SIGNALS
};

#endif
